=== GYKevin190/CBOYZF_XMLGyak/XMLTaskCBOYZF/XMLSchemaCBOYZF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 


<!-- Egyszerű típusok kigyűjtése, saját típusok meghatározása, megszorítás -->
<xs:element name="ár" type="xs:positiveInteger"/>
<xs:element name="raktárba_érkezés" type="xs:date"/>
<xs:element name="márka" type="xs:string"/>
<xs:element name="név" type="xs:string"/>
<xs:element name="várható_érkezés" type="xs:date"/>
<xs:element name="csomagolás_típusa" type="xs:string"/>
<xs:element name="Helyzet" type="xs:string"/>
<xs:element name="VásárlásIdőpontja" type="xs:date"/>
<xs:element name="VásároltTermék" type="xs:string"/>
<xs:element name= "Telefonszám" type="TelefonszámTípus"/>


<xs:simpleType name="TelefonszámTípus">
    <xs:restriction base="xs:string">
        <xs:pattern value="\d{4}-\d{3}-\d{4}" />
    </xs:restriction>
</xs:simpleType>

<!--Komplex típusokhoz saját típus meghatározása, sorrendiség, számosság etc. -->

<xs:complexType name="raktárTípus">
    <xs:sequence>
        <xs:element ref="ár" />
        <xs:element ref="raktárba_érkezés" maxOccurs="1" />
        <xs:element name="cím">
            <xs:complexType> 
                <xs:sequence>
                    <xs:element name="Isz" type="xs:integer" />
                    <xs:element name="Város" type="xs:string" />
                    <xs:element name="Utca" type="xs:string" />
                    <xs:element name="házszám" type="xs:integer" />
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="raktár_id" type="xs:integer" use="required" />
</xs:complexType>


<xs:complexType name="GyárihibásTípus">
    <xs:sequence>
        <xs:element ref="ár" />
        <xs:element ref="márka" maxOccurs="1" />
        <xs:element ref="név" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="gyárihibás_id" type="xs:integer" use="required" />
    <xs:attribute name="raktár" type="xs:integer" use="required" />
</xs:complexType>

<xs:complexType name="B_RTípus">
    <xs:attribute name="darabszám" type="xs:integer" use="required" />
    <xs:attribute name="raktár" type="xs:integer" use="required" />
    <xs:attribute name="beszállító" type="xs:integer" use="required" />
</xs:complexType>

<xs:complexType name="beszállítóTípus">
    <xs:sequence>
        <xs:element ref="várható_érkezés" maxOccurs="1"/>
        <xs:element ref="ár" />
        <xs:element ref="csomagolás_típusa" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="raktár" type="xs:integer" use="required" />
    <xs:attribute name="beszállító_id" type="xs:integer" use="required" />
</xs:complexType>

<xs:complexType name="futárTípus">
    <xs:sequence>
        <xs:element ref="Helyzet" maxOccurs="1"/>
        <xs:element ref="várható_érkezés" maxOccurs="1" />
        <xs:element ref="ár" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="Rendelés_szám" type="xs:integer" use="required" />
    <xs:attribute name="raktár" type="xs:integer" use="required" />
</xs:complexType>

<xs:complexType name="ügyfélTípus">
    <xs:sequence>
        <xs:element ref="VásárlásIdőpontja" maxOccurs="1" />
        <xs:element ref="VásároltTermék" maxOccurs="unbounded"/>
        <xs:element ref="Telefonszám" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="cím">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="Isz" type="xs:integer" />
                    <xs:element name="Város" type="xs:string" />
                    <xs:element name="Utca" type="xs:string" />
                    <xs:element name="házszám" type="xs:integer" />
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="Csomagszám" type="xs:integer" use="required" />
    <xs:attribute name="futár" type="xs:integer" use="required" />
</xs:complexType>

<!-- Gyökérelemtől az elemek felhasználása -->

<xs:element name="Csomag_követés_CBOYZF">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="raktár" type="raktárTípus" minOccurs="0" maxOccurs="100"/>
                <xs:element name="Gyárihibás" type="GyárihibásTípus" minOccurs="0" maxOccurs="100"/>
                <xs:element name="B_R" type="B_RTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="beszállító" type="beszállítóTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="futár" type="futárTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="ügyfél" type="ügyfélTípus" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
         <!-- Elsődleges kulcsok -->

        <xs:key name="raktár_kulcs">
            <xs:selector xpath="raktár"/>
            <xs:field xpath="@raktár_id"/>
        </xs:key>

        <xs:key name="gyárihibás_kulcs">
            <xs:selector xpath="Gyárihibás"/>
            <xs:field xpath="@gyárihibás_id"/>
        </xs:key>

        <xs:key name="B_R_kulcs">
            <xs:selector xpath="B_R"/>
            <xs:field xpath="@darabszám"/>
        </xs:key>

        <xs:key name="beszállító_kulcs">
            <xs:selector xpath="beszállító"/>
            <xs:field xpath="@beszállító_id"/>
        </xs:key>

        <xs:key name="futár_kulcs">
            <xs:selector xpath="futár"/>
            <xs:field xpath="@Rendelés_szám"/>
        </xs:key>

        <xs:key name="ügyfél_kulcs">
            <xs:selector xpath="ügyfél"/>
            <xs:field xpath="@Csomagszám"/>
        </xs:key>

        <!-- Idegen kulcsok -->

        <xs:keyref name="gyárihibás_raktár_kulcs" refer="raktár_kulcs">
            <xs:selector xpath="Gyárihibás"/>
            <xs:field xpath="@raktár"/>
        </xs:keyref>


        <xs:keyref name="B_R_raktár_kulcs" refer="raktár_kulcs">
            <xs:selector xpath="B_R"/>
            <xs:field xpath="@raktár"/>
        </xs:keyref>

        
        <xs:keyref name="B_R_beszállító_kulcs" refer="beszállító_kulcs">
            <xs:selector xpath="B_R"/>
            <xs:field xpath="@beszállító"/>
        </xs:keyref>

        <xs:keyref name="futár_raktár_kulcs" refer="raktár_kulcs">
            <xs:selector xpath="futár"/>
            <xs:field xpath="@raktár"/>
        </xs:keyref>

        <xs:keyref name="ügyfél_futár_kulcs" refer="futár_kulcs">
            <xs:selector xpath="ügyfél"/>
            <xs:field xpath="@futár"/>
        </xs:keyref>
        
        <!-- Az 1:1 kapcsolat megvalósítás -->
        <xs:unique name="Gyárihiba_Raktár_egyegy">
            <xs:selector xpath="Gyárihibás"/>
            <xs:field xpath="@raktár"/>
        </xs:unique>

    </xs:element>    

</xs:schema>

=== GYKevin190/CBOYZF_XMLGyak/XMLTaskCBOYZF/XMLCBOYZF1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Csomag_követés_CBOYZF xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaCBOYZF.xsd">
    <raktár raktár_id="01">
    <ár>
        500
    </ár>
    <raktárba_érkezés>
        2023-10-10
    </raktárba_érkezés>
    <cím>
        <Isz>
            3881
        </Isz>
        <Város>
            Abaújszántó
        </Város>
        <Utca>
            Béke út
        </Utca>
        <házszám>
            1
        </házszám>
    </cím>
</raktár>
    <raktár raktár_id="02">
    <ár>
        1500
    </ár>
    <raktárba_érkezés>
        2023-10-11
    </raktárba_érkezés>
    <cím>
        <Isz>
            3881
        </Isz>
        <Város>
            Abaújszántó
        </Város>
        <Utca>
            Béke út
        </Utca>
        <házszám>
            2
        </házszám>
    </cím>
</raktár>
    <raktár raktár_id="03">
    <ár>
        1500
    </ár>
    <raktárba_érkezés>
        2023-10-12
    </raktárba_érkezés>
    <cím>
        <Isz>
            3860
        </Isz>
        <Város>
            Encs
        </Város>
        <Utca>
            Rákóczi út
        </Utca>
        <házszám>
            3
        </házszám>
    </cím>
</raktár>
    <Gyárihibás gyárihibás_id="11" raktár="01">
    <ár>
        100
    </ár>
    <márka>
        Samsung
    </márka>
    <név>
        Telefon
    </név>
</Gyárihibás>
    <Gyárihibás gyárihibás_id="12" raktár="02">
    <ár>
        200
    </ár>
    <márka>
        Apple
    </márka>
    <név>
        Airpods
    </név>
</Gyárihibás>
    <Gyárihibás gyárihibás_id="13" raktár="03">
    <ár>
        300
    </ár>
    <márka>
        Sony
    </márka>
    <név>
        Playstation
    </név>
</Gyárihibás>
    <B_R beszállító="21" darabszám="5" raktár="01">
</B_R>
    <B_R beszállító="22" darabszám="10" raktár="01">
</B_R>
    <B_R beszállító="23" darabszám="25" raktár="03">
</B_R>
    <beszállító beszállító_id="21" raktár="01">
    <várható_érkezés>
        2023-10-18
    </várható_érkezés>
    <ár>
        50000
    </ár>
    <csomagolás_típusa>
        Fólia
    </csomagolás_típusa>
</beszállító>
    <beszállító beszállító_id="22" raktár="02">
    <várható_érkezés>
        2023-10-16
    </várható_érkezés>
    <ár>
        40000
    </ár>
    <csomagolás_típusa>
        Boríték
    </csomagolás_típusa>
</beszállító>
    <beszállító beszállító_id="23" raktár="03">
    <várható_érkezés>
        2023-10-19
    </várható_érkezés>
    <ár>
        30000
    </ár>
    <csomagolás_típusa>
        Doboz
    </csomagolás_típusa>
</beszállító>
    <futár Rendelés_szám="31" raktár="01">
    <Helyzet>
        Úton
    </Helyzet>
    <várható_érkezés>
        2023-10-28
    </várható_érkezés>
    <ár>
        1500
    </ár>
</futár>
    <futár Rendelés_szám="32" raktár="02">
    <Helyzet>
        Áll
    </Helyzet>
    <várható_érkezés>
        2023-10-23
    </várható_érkezés>
    <ár>
        4000
    </ár>
</futár>
    <futár Rendelés_szám="33" raktár="03">
    <Helyzet>
        Felfüggesztve
    </Helyzet>
    <várható_érkezés>
        2023-10-29
    </várható_érkezés>
    <ár>
        2500
    </ár>
</futár>
    <ügyfél Csomagszám="41" futár="31">
    <VásárlásIdőpontja>
        2023-10-14
    </VásárlásIdőpontja>
    <VásároltTermék>
        Iphone 13 pro max
    </VásároltTermék>
    <Telefonszám>
        0620-714-9284
    </Telefonszám>
    <cím>
        <Isz>
            3881
        </Isz>
        <Város>
            Abaújszántó
        </Város>
        <Utca>
            Rákóczi út
        </Utca>
        <házszám>
            3
        </házszám>
    </cím>
</ügyfél>
    <ügyfél Csomagszám="42" futár="32">
    <VásárlásIdőpontja>
        2023-10-12
    </VásárlásIdőpontja>
    <VásároltTermék>
        Smasung galaxy A52
    </VásároltTermék>
    <Telefonszám>
        0620-394-2132
    </Telefonszám>
    <Telefonszám>
        0630-153-4576
    </Telefonszám>
    <cím>
        <Isz>
            3881
        </Isz>
        <Város>
            Abaújszántó
        </Város>
        <Utca>
            Béke út
        </Utca>
        <házszám>
            4
        </házszám>
    </cím>
</ügyfél>
    <ügyfél Csomagszám="43" futár="33">
    <VásárlásIdőpontja>
        2023-10-18
    </VásárlásIdőpontja>
    <VásároltTermék>
        Xbox Series X
    </VásároltTermék>
    <Telefonszám>
        0670-345-2376
    </Telefonszám>
    <cím>
        <Isz>
            3881
        </Isz>
        <Város>
            Abaújszántó
        </Város>
        <Utca>
            Kazincy út
        </Utca>
        <házszám>
            19
        </házszám>
    </cím>
</ügyfél>
</Csomag_követés_CBOYZF>
